echo off
color 2
:menu
echo =================================================
echo        WELCOME TO WINDOWS TWEAKS MENU
echo                     V3.0.0
echo =================================================
echo                      MENU
echo  1.Disabled Services        4.Debloat
echo  2.Optimization Regedit     5.All
echo  3.Create restore point     6.Exit
set /p selects="Select : "

if "%selects%"=="1" goto services
if "%selects%"=="2" goto regedit
if "%selects%"=="3" goto restorepoint
if "%selects%"=="4" goto debloat
if "%selects%"=="5" goto alltweaks
if "%selects%"=="6" exit

:services
echo start disabled some services.....
echo disabled ActiveX Installer (AxInstSV).....
sc config "AxInstSV" start=disabled
echo disabled Auto Time Zone Update.....
sc config "tzautoupdate" start=disabled
echo disabled Connected User Experiences and Telemetry.....
sc config "DiagTrack" start=disabled
echo disabled Diagnostic Policy Service.....
sc config "DPS" start=disabled
echo disabled Downloaded Maps Manager.....
sc config "MapsBroker" start=disabled
echo disabled ELAN Service.....
sc config "ETDService" start=disabled
echo disabled Geolocation Service.....
sc config "lfsvc" start=disabled
echo disabled Net.Tcp Port Sharing Service.....
sc config "NetTcpPortSharing" start=disabled
echo disabled OpenSSH Authentication Agent.....
sc config "ssh-agent" start=disabled
echo disabled Parental Controls.....
sc config "WpcMonSvc" start=disabled
echo disabled Print Spooler.....
sc config "Spooler" start=disabled
echo disabled Realtek Audio Universal Service.....
sc config "RtkAudioUniversalService" start=disabled
echo disabled Realtek Bluetooth Device Manager Service.....
sc config "RtkBtManServ" start=disabled
echo disabled Remote Desktop Configuration.....
sc config "SessionEnv" start=disabled
echo disabled Remote Desktop Services.....
sc config "TermService" start=disabled
echo disabled Remote Desktop Services UserMode Port Redirector.....
sc config "UmRdpService" start=disabled
echo disabled Remote Registry.....
sc config "RemoteRegistry" start=disabled
echo disabled Retail Demo Service.....
sc config "RetailDemo" start=disabled
echo disabled Routing and Remote Access.....
sc config "RemoteAccess" start=disabled
echo disabled Secondary Logon.....
sc config "seclogon" start=disabled
echo disabled Payments and NFC/SE Manager.....
sc config "SEMgrSvc" start=disabled
echo disabled Print Device Configuration Service.....
sc config "PrintDeviceConfigurationService" start=disabled
echo disabled Printer Extensions and Notifications.....
sc config "PrintNotify" start=disabled
echo disabled Shared PC Account Manager.....
sc config "shpamsvc" start=disabled
echo disabled Smart Card.....
sc config "SCardSvr" start=disabled
echo disabled Smart Card Device Enumeration Service.....
sc config "ScDeviceEnum" start=disabled
echo disabled Smart Card Removal Policy.....
sc config "SCPolicySvc" start=disabled
echo disabled Sound Research SECOMN Service.....
sc config "SECOMNService" start=disabled
echo disabled SysMain.....
sc config "SysMain" start=disabled
echo disabled WalletService.....
sc config "WalletService" start=disabled
echo disabled Windows Error Reporting Service.....
sc config "WerSvc" start=disabled
echo disabled Windows Search.....
sc config "WSearch" start=disabled
echo disabled Xbox Accessory Management Service.....
sc config "XboxGipSvc" start=disabled
echo disabled Xbox Live Auth Manager.....
sc config "XblAuthManager" start=disabled
echo disabled Xbox Live Game Save.....
sc config "XblGameSave" start=disabled
echo disabled Xbox Live Networking Service.....
sc config "XboxNetApiSvc" start=disabled
goto menu

:regedit
echo start optimization regedit.....
reg add "HKCU"\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseFeatureUpdatesEndTime /t REG_SZ /d "2099-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseQualityUpdatesEndTime /t REG_SZ /d "2099-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseUpdatesExpiryTime /t REG_SZ /d "2099-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseFeatureUpdatesStartTime /t REG_SZ /d "2025-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseQualityUpdatesStartTime /t REG_SZ /d "2025-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseUpdatesStartTime /t REG_SZ /d "2025-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\0" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\1" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\2" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\3" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\4" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\5" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\6" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\7" /v ProcessorNameString /t REG_SZ /d "Hello 3 7Pro" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy" /v LetAppsRunInBackground /t REG_DWORD /d 2 /f
goto menu


:restorepoint
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore" /v SystemRestorePointCreationFrequency /t REG_DWORD /d 0 /f
powershell -Command "CheckPoint-Computer -Description 'HelloOS Delete' -RestorePointType MODIFY_SETTINGS"
goto menu

:debloat
echo start debloat.....
echo uninstall name.....
powershell -Command "Get-AppxPackage *name* | Remove-AppxPackage"

:alltweaks
echo coming soon in V3.5.0