echo off
color 2
:menu
echo =================================================
echo        WELCOME TO WINDOWS TWEAKS MENU
echo                     V3.5.0
echo =================================================
echo                      MENU
echo  1.Disable Services         5.Debloat
echo  2.Optimization Regedit     6.All
echo  3.Create restore point     7.Exit
echo  4.Disable Task Schedule
set /p selects="Select : "

if "%selects%"=="1" goto services
if "%selects%"=="2" goto regedit
if "%selects%"=="3" goto restorepoint
if "%selects%"=="4" goto taskschedule
if "%selects%"=="5" goto debloat
if "%selects%"=="6" goto alltweaks
if "%selects%"=="7" exit

:services
echo start disabled some services.....
echo disabled ActiveX Installer (AxInstSV).....
sc config "AxInstSV" start=disabled
echo disabled Auto Time Zone Update.....
sc config "tzautoupdate" start=disabled
echo disabled Connected User Experiences and Telemetry.....
sc config "DiagTrack" start=disabled
echo disabled Diagnostic Policy Service.....
sc config "DPS" start=disabled
echo disabled Downloaded Maps Manager.....
sc config "MapsBroker" start=disabled
echo disabled ELAN Service.....
sc config "ETDService" start=disabled
echo disabled Geolocation Service.....
sc config "lfsvc" start=disabled
echo disabled Net.Tcp Port Sharing Service.....
sc config "NetTcpPortSharing" start=disabled
echo disabled OpenSSH Authentication Agent.....
sc config "ssh-agent" start=disabled
echo disabled Parental Controls.....
sc config "WpcMonSvc" start=disabled
echo disabled Print Spooler.....
sc config "Spooler" start=disabled
echo disabled Realtek Audio Universal Service.....
sc config "RtkAudioUniversalService" start=disabled
echo disabled Realtek Bluetooth Device Manager Service.....
sc config "RtkBtManServ" start=disabled
echo disabled Remote Desktop Configuration.....
sc config "SessionEnv" start=disabled
echo disabled Remote Desktop Services.....
sc config "TermService" start=disabled
echo disabled Remote Desktop Services UserMode Port Redirector.....
sc config "UmRdpService" start=disabled
echo disabled Remote Registry.....
sc config "RemoteRegistry" start=disabled
echo disabled Retail Demo Service.....
sc config "RetailDemo" start=disabled
echo disabled Routing and Remote Access.....
sc config "RemoteAccess" start=disabled
echo disabled Secondary Logon.....
sc config "seclogon" start=disabled
echo disabled Payments and NFC/SE Manager.....
sc config "SEMgrSvc" start=disabled
echo disabled Print Device Configuration Service.....
sc config "PrintDeviceConfigurationService" start=disabled
echo disabled Printer Extensions and Notifications.....
sc config "PrintNotify" start=disabled
echo disabled Shared PC Account Manager.....
sc config "shpamsvc" start=disabled
echo disabled Smart Card.....
sc config "SCardSvr" start=disabled
echo disabled Smart Card Device Enumeration Service.....
sc config "ScDeviceEnum" start=disabled
echo disabled Smart Card Removal Policy.....
sc config "SCPolicySvc" start=disabled
echo disabled Sound Research SECOMN Service.....
sc config "SECOMNService" start=disabled
echo disabled SysMain.....
sc config "SysMain" start=disabled
echo disabled WalletService.....
sc config "WalletService" start=disabled
echo disabled Windows Error Reporting Service.....
sc config "WerSvc" start=disabled
echo disabled Windows Search.....
sc config "WSearch" start=disabled
echo disabled Xbox Accessory Management Service.....
sc config "XboxGipSvc" start=disabled
echo disabled Xbox Live Auth Manager.....
sc config "XblAuthManager" start=disabled
echo disabled Xbox Live Game Save.....
sc config "XblGameSave" start=disabled
echo disabled Xbox Live Networking Service.....
sc config "XboxNetApiSvc" start=disabled
goto menu

:regedit
echo start optimization regedit.....
reg add "HKCU"\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseFeatureUpdatesEndTime /t REG_SZ /d "2099-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseQualityUpdatesEndTime /t REG_SZ /d "2099-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseUpdatesExpiryTime /t REG_SZ /d "2099-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseFeatureUpdatesStartTime /t REG_SZ /d "2025-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseQualityUpdatesStartTime /t REG_SZ /d "2025-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v PauseUpdatesStartTime /t REG_SZ /d "2025-12-30T02:17:44Z" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy" /v LetAppsRunInBackground /t REG_DWORD /d 2 /f
goto menu


:restorepoint
echo start create restorepoint.....
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore" /v SystemRestorePointCreationFrequency /t REG_DWORD /d 0 /f
powershell -Command "CheckPoint-Computer -Description 'HelloOS Delete' -RestorePointType MODIFY_SETTINGS"
goto menu

:taskschedule
echo start disable some tasks schedule.....
echo disable StartupAppTask......
schtasks.exe /change /tn "\Microsoft\Windows\Application Experience\StartupAppTask" /disable
echo disable MapsUpdateTask.....
schtasks.exe /change /tn "\Microsoft\Windows\Maps\MapsUpdateTask" /disable
echo disable MapsToastTask.....
schtasks.exe /change /tn "\Microsoft\Windows\Maps\MapsToastTask" /disable
echo disable UsbCeip.....
schtasks.exe /change /tn "\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip" /disable
echo disable Consolidator.....
schtasks.exe /change /tn "\Microsoft\Windows\Customer Experience Improvement Program\Consolidator" /disable
echo disable XblGameSaveTask.....
schtasks.exe /change /tn "\Microsoft\XblGameSave\XblGameSaveTask" /disable
goto menu

:debloat
echo start debloat.....
echo uninstall xbox.....
powershell -Command "Get-AppxPackage *xbox* | Remove-AppxPackage"
echo uninstall paint.....
powershell -Command "Get-AppxPackage *paint* | Remove-AppxPackage"
echo uninstall bing.....
powershell -Command "Get-AppxPackage *bing* | Remove-AppxPackage"
echo uninstall clock.....
powershell -Command "Get-AppxPackage *clock* | Remove-AppxPackage"
echo uninstall paint.....
powershell -Command "Get-AppxPackage *paint* | Remove-AppxPackage"
echo uninstall widget.....
powershell -Command "Get-AppxPackage *widget* | Remove-AppxPackage"
echo uninstall calc.....
powershell -Command "Get-AppxPackage *calc* | Remove-AppxPackage"
echo uninstall maps.....
powershell -Command "Get-AppxPackage *maps* | Remove-AppxPackage"
goto menu

:alltweaks
echo coming soon in V3.5.0